apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service

    spec:
      # 앱이 worker 노드에만 뜨도록 설정
      nodeSelector:
        workload: app
      containers:
        - name: chat-app
          image: daul0519/chat-service:v2
          ports:
            - containerPort: 1005
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                    name: db-secret
                    key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: db-secret
                    key: password

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mongo-secret
                    key: password