apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service

    spec:
      # 앱이 worker 노드에만 뜨도록 설정
      nodeSelector:
        workload: app
      containers:
        - name: gateway-app
          image: gcr.io/[프로젝트ID]/gateway-service:latest
          ports:
            - containerPort: 1000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod