apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service

    spec:
      # 앱이 worker 노드에만 뜨도록 설정
      nodeSelector:
        workload: app
      containers:
        - name: user-app
          image: daul0519/user-service:v2
          ports:
            - containerPort: 1003
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password

            - name: bucket-url
              valueFrom:
                secretKeyRef:
                  name: bucket-url
                  key: bucketurl

            - name: jwt_secret
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
