export const FEEDSERVICE_API = process.env.NEXT_PUBLIC_FEEDSERVICE_API
export const NOTIFICATIONSERVEICE_API = process.env.NEXT_PUBLIC_NOTIFICATIONSERVEICE_API!;
export const USERSERVICE_API = process.env.NEXT_PUBLIC_USERSERVICE_API!;
export const BLOGSERVICE_API = process.env.NEXT_PUBLIC_BLOGSERVICE_API!;
export const CHATSERVICE_API = process.env.NEXT_PUBLIC_CHATSERVICE_API!;
export const GATEWAY_API_URL = process.env.NEXT_PUBLIC_GATEWAY_API!;
export const COMMUNITYSERVICE_API = process.env.NEXT_PUBLIC_COMMUNITYSERVICE_API!;
export const FRIENDSSERVICE_API = process.env.NEXT_PUBLIC_FRIENDSSERVICE_API!;

if (!FEEDSERVICE_API) throw new Error('NEXT_PUBLIC_FEEDSERVICE_API 누락!');
if (!NOTIFICATIONSERVEICE_API) throw new Error('NEXT_PUBLIC_NOTIFICATIONSERVEICE_API 누락!');
if (!USERSERVICE_API) throw new Error('NEXT_PUBLIC_USERSERVICE_API 누락!');
if (!BLOGSERVICE_API) throw new Error('NEXT_PUBLIC_BLOGSERVICE_API 누락!');
if (!CHATSERVICE_API) throw new Error('NEXT_PUBLIC_CHATSERVICE_API 누락!');
if (!GATEWAY_API_URL) throw new Error('NEXT_PUBLIC_GATEWAY_API 누락!');
if (!COMMUNITYSERVICE_API) throw new Error('NEXT_PUBLIC_COMMUNITYSERVICE_API 누락!');
if (!FRIENDSSERVICE_API) throw new Error('NEXT_PUBLIC_FRIENDSSERVICE_API 누락!');
